dbt_project:
  target: dev-postgres-transform
  outputs:
    dev-snowflake:
      type: snowflake
      account: [account id]
      # User/password auth
      user: [username]
      password: [password]
      role: [user role]
      database: [database name]
      warehouse: [warehouse name]
      schema: [dbt schema]
      threads: [1 or more]
      client_session_keep_alive: False
      query_tag: anything
      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: False # default: false (available v1.4+)

    dev-postgres-transform:
      type: postgres
      host: localhost
      user: username
      password: password
      port: 5432
      dbname: username # or database instead of dbname
      schema: transform
      #connect_timeout: 30 
      #role: username
      